Updates to Show RTI properties on Grid & BNData Update
Mozu/Mozu.Integrations.RTI.Widgets pull request #21
Opened 2018-06-13 15:15 UTC by naminder-trantor

2018-06-13 16:06 UTC, shelkeller commented
We try to avoid having <script> tags in our hypr templates. Is there a reason you haven't put the rti-product-tiles.hypr.live script logic in rti-rec-scripts.js?

2018-06-13 20:59 UTC, Amjcraft requested changes
I agree with shelkeller. There should be no real reason to have inline javascript on the rti-products-tiles.hypr page. Move this into one of the widgets js files please.

2018-06-14 05:27 UTC, naminder-trantor commented
@shelkeller @Amjcraft Script is removed from hypr.live. Please review

2018-06-14 15:01 UTC, Amjcraft approved these changes

2018-06-14 15:01 UTC, merged